//! OpenCode plugin emit — writes a TypeScript plugin file that intercepts
//! tool.execute.before for the bash tool and rewrites Gradle invocations.
//!
//! The plugin is a self-contained TS module; it shells out to `gw rewrite`
//! to keep rewrite logic single-source-of-truth (avoids re-implementing
//! gradle detection in TS).

use anyhow::{anyhow, Result};
use std::path::Path;

use super::agent::{AgentStatus, InstallOutcome, UninstallOutcome};
use super::settings::write_text_with_backup;

const PLUGIN_TS: &str = r#"// gw — Gradle output filter (https://github.com/AndVl1/gw)
// Auto-generated by `gw init --agent opencode`. Edit at your own risk.
import type { Plugin } from "@opencode-ai/plugin"
import { execFileSync } from "node:child_process"

export const GwGradleFilter: Plugin = async () => ({
  "tool.execute.before": async (input, output) => {
    if (input.tool !== "bash") return
    const cmd: string | undefined = output?.args?.command
    if (!cmd || cmd.startsWith("gw ")) return
    try {
      const rewritten = execFileSync("gw", ["rewrite", "--", cmd], {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim()
      if (rewritten && rewritten !== cmd) {
        output.args.command = rewritten
      }
    } catch {
      // gw not installed or not on PATH — leave command untouched.
    }
  },
})
"#;

const GW_PLUGIN_MARKER: &str = "Auto-generated by `gw init --agent opencode`";

pub fn status(path: &Path) -> Result<AgentStatus> {
    if !path.exists() {
        return Ok(AgentStatus::NoFile);
    }
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow!("read {} failed: {e}", path.display()))?;
    if content.contains(GW_PLUGIN_MARKER) {
        Ok(AgentStatus::Installed)
    } else {
        Ok(AgentStatus::NotInstalled)
    }
}

pub fn install(path: &Path) -> Result<InstallOutcome> {
    if path.exists() {
        let existing = std::fs::read_to_string(path)
            .map_err(|e| anyhow!("read {} failed: {e}", path.display()))?;
        if existing.contains(GW_PLUGIN_MARKER) {
            return Ok(InstallOutcome::AlreadyInstalled);
        }
    }
    write_text_with_backup(path, PLUGIN_TS)?;
    Ok(InstallOutcome::Installed)
}

pub fn uninstall(path: &Path) -> Result<UninstallOutcome> {
    if !path.exists() {
        return Ok(UninstallOutcome::NoFile);
    }
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow!("read {} failed: {e}", path.display()))?;
    if !content.contains(GW_PLUGIN_MARKER) {
        return Ok(UninstallOutcome::NotPresent);
    }
    std::fs::remove_file(path).map_err(|e| anyhow!("remove {} failed: {e}", path.display()))?;
    Ok(UninstallOutcome::Removed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn install_writes_plugin_file() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("plugin/gw.ts");
        assert!(matches!(install(&path).unwrap(), InstallOutcome::Installed));
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("@opencode-ai/plugin"));
        assert!(content.contains(GW_PLUGIN_MARKER));
    }

    #[test]
    fn install_is_idempotent() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("gw.ts");
        install(&path).unwrap();
        assert!(matches!(
            install(&path).unwrap(),
            InstallOutcome::AlreadyInstalled
        ));
    }

    #[test]
    fn uninstall_removes_only_our_plugin() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("gw.ts");
        std::fs::write(&path, "// not ours").unwrap();
        assert!(matches!(
            uninstall(&path).unwrap(),
            UninstallOutcome::NotPresent
        ));
        install(&path).unwrap();
        assert!(matches!(
            uninstall(&path).unwrap(),
            UninstallOutcome::Removed
        ));
        assert!(!path.exists());
    }
}
